return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	version = "*",
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	config = function()
		-- Ayu colors
		local colors = {
			bg = "#0b0e14",
			bg_alt = "#0d1017",
			fg = "#bfbdb6",
			fg_dim = "#565b66",
			accent = "#e6b450",
			orange = "#ff8f40",
			blue = "#59c2ff",
			cyan = "#73b8ff",
			purple = "#d2a6ff",
			green = "#aad94c",
		}

		require("barbecue").setup({
			theme = {
				normal = { fg = colors.fg_dim, bg = colors.bg_alt },
				ellipsis = { fg = colors.fg_dim },
				separator = { fg = colors.fg_dim },
				modified = { fg = colors.accent },
				dirname = { fg = colors.fg_dim },
				basename = { fg = colors.fg, bold = true },
				context = { fg = colors.fg_dim },
				-- Context kinds
				context_file = { fg = colors.fg },
				context_module = { fg = colors.blue },
				context_namespace = { fg = colors.blue },
				context_package = { fg = colors.blue },
				context_class = { fg = colors.orange },
				context_method = { fg = colors.purple },
				context_property = { fg = colors.cyan },
				context_field = { fg = colors.cyan },
				context_constructor = { fg = colors.orange },
				context_enum = { fg = colors.orange },
				context_interface = { fg = colors.blue },
				context_function = { fg = colors.purple },
				context_variable = { fg = colors.fg },
				context_constant = { fg = colors.accent },
				context_string = { fg = colors.green },
				context_number = { fg = colors.accent },
				context_boolean = { fg = colors.accent },
				context_array = { fg = colors.cyan },
				context_object = { fg = colors.orange },
				context_key = { fg = colors.cyan },
				context_null = { fg = colors.fg_dim },
				context_enum_member = { fg = colors.cyan },
				context_struct = { fg = colors.orange },
				context_event = { fg = colors.purple },
				context_operator = { fg = colors.fg },
				context_type_parameter = { fg = colors.orange },
			},
			show_dirname = false,
			show_basename = true,
			show_modified = true,
			modified = function(bufnr)
				return vim.bo[bufnr].modified
			end,
			exclude_filetypes = {
				"NvimTree",
				"alpha",
				"dashboard",
				"Trouble",
				"lazy",
				"mason",
				"toggleterm",
				"qf",
				"help",
				"netrw",
				"oil",
			},
			kinds = {
				File = "",
				Module = "",
				Namespace = "󰌗",
				Package = "",
				Class = "󰌗",
				Method = "󰆧",
				Property = "",
				Field = "",
				Constructor = "",
				Enum = "󰕘",
				Interface = "",
				Function = "󰊕",
				Variable = "󰆧",
				Constant = "󰏿",
				String = "󰀬",
				Number = "󰎠",
				Boolean = "◩",
				Array = "󰅪",
				Object = "󰅩",
				Key = "󰌋",
				Null = "󰟢",
				EnumMember = "",
				Struct = "󰌗",
				Event = "",
				Operator = "󰆕",
				TypeParameter = "󰊄",
			},
			lead_custom_section = function()
				return " "
			end,
		})
	end,
}
