# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = nemo
$applauncher = wofi
$terminal = ghostty
$idlehandler = hypridle

# Screenshots - save to folder + copy to clipboard + notify
$screenshot-dir = ~/Pictures/Screenshots
$shot-region = grimblast --notify copysave area $screenshot-dir/$(date +%Y-%m-%d_%H-%M-%S).png
$shot-window = grimblast --notify copysave active $screenshot-dir/$(date +%Y-%m-%d_%H-%M-%S).png
$shot-screen = grimblast --notify copysave output $screenshot-dir/$(date +%Y-%m-%d_%H-%M-%S).png
