# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/colors.conf

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = $accent
    col.inactive_border = $bg_light
    layout = dwindle

    # https://wiki.hyprland.org/Configuring/Variables/#snap
    snap {
        enabled = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#group
group {
    col.border_active = $accent
    col.border_inactive = $bg_light
    col.border_locked_active = $accent_dim
    col.border_locked_inactive = $bg_mid

    # https://wiki.hyprland.org/Configuring/Variables/#groupbar
    groupbar {
        font_family = "MesloLGS Nerd Font"
        font_size = 10
        text_color = $fg
        col.active = $accent
        col.inactive = $bg_mid
        col.locked_active = $accent_dim
        col.locked_inactive = $bg_light
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    font_family = "MesloLGS Nerd Font"
    splash_font_family = "MesloLGS Nerd Font"
    disable_hyprland_logo = true
    col.splash = $accent
    background_color = $bg_dark
    enable_swallow = true
    swallow_regex = ^(nautilus|nemo|thunar|btrfs-assistant.)$
    focus_on_activate = true
    vrr = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#render
render {
   direct_scanout = true
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    special_scale_factor = 0.9
    pseudotile = true
    preserve_split = true
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
    special_scale_factor = 0.9
}
